sudo: required
dist: xenial
addons:
  apt:
    packages: haveged
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
before_script:
  - echo $JAVA_OPTS
  - export JAVA_OPTS=-Xmx4G
install: true
script:
  - java -version
  - ulimit -a
  - TERM=dumb ./gradlew jpos:assemble jpos:check --info
deploy:
  provider: script
  script: bash .travis/update-gh-pages.sh
  on:
    branch: master
env:
  global:
    secure: ZWDnTNCsRaxOV4hPiWslj1ieKwYjuxBA4COHFVApxr8TBcQEwhPAzo+b+WbDsi45rJkk/Ee9Du0+mbT//x3TTK78fePg6EDk0WBSmWRUFC3eITgTmUJe7Qh5VOUZOdz9vFaYH8080/CB4VyygJuSp2XLte+S/MVSoXVVABrNggU=
notifications:
  slack:
    secure: opKU+4jJWYuhq5STCVW2cvxEq/1/xY17xpxGKoJXWA+RbhPo+viT5uJLmb67HwdmvQNwUVAW6uOLO7SDOmpGh5oAwpI74DrA0y6uEzN6GgzutZDBY5oCMRYCGi/5xNOuzDdsryDtSJvXWLxyCysnTrAqqQ9XdOnRK/ZqSIeQg+s=
matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
  allow_failures:
    - jdk: openjdk9
    - jdk: openjdk10
